# This action finds in-progress Action jobs for the same branch, and cancels
# them. There's little point in continuing to run superseded jobs.

name: cancel

on:
  push:

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.12.0
      with:
        access_token: ${{ github.token }}
        workflow_id: test.yml
